### PR TITLE
Issue10 Generate a random seed during the run

### LINKED ISSUE #1: Compute precision-recall curves and ROC curves after combining folds
Right now, we compute AUPRC and AUROC for each fold. We should combine the cross-validation scores for all folds into one list, and compute precison-recall and ROC curves and various scores (AUPRC, AUROC, average precision, etc.) on the combined list. This function should be equally applicable to all types of evaluations.

### LINKED ISSUE #10: Generate a random seed during the run
Currently, the pipeline uses a random seed provided through the config file. We want the random seed to be generated during an active run of the code. 
Random seed through the config file should only be used to regenerate an old result or for debugging purposes.

### PR DESCRIPTION
**Pull request by malabikasen**
`randSeed` should be used as a parameter in the config file to reproduce the result else, the code generates a random number in `SGRN/__init__.py`

### CODE REVIEW

**Comment by tmmurali** [comment]
Which version of numpy are we using?

**Comment by malabikasen** [comment]
> Which version of numpy are we using?

1.19.2 @tmmurali

**Comment by tmmurali** [comment]
@adyprat @malabikasen please see https://numpy.org/doc/stable/reference/random/index.html on how to initialise random number generators and how to pass seeds to them.

I am also concerned that we are passing the same seed in lines 43-45 of SGRN/GAERunner.py. Are we not potentially making these random numbers depend on each other?

We can discuss here.

**Comment by malabikasen** [comment]
> I am also concerned that we are passing the same seed in lines 43-45 of SGRN/GAERunner.py. Are we not potentially making these random numbers depend on each other?

We are. Don't we want the same random seed which is initialized randomly (and not passed through config file) at the start of a run to be used through out that run? That's what my understanding was.

**Comment by tmmurali** [comment]
If there are different sequences of random numbers being generated in the code, we don't want them to be correlated. We should use three different seeds or three different random number generators.

The only time it is "ok" for these to be correlated is when we pass an external seed, e.g., when we are debugging or trying to regenerate an earlier result.

**Pull request closed without merging**
